### ISSUE TITLE
How do I share my ipynb file?

### ISSUE THREAD

**Issue by Hetarth02** [networkx/notebooks#16]
@MridulS I have created a documentation in jupyter notebook regarding Basic functions of Bipartite graphs and I want to share it with you so you can check and approve or give me feedback on how to improve and what to add so it can be documented. Please, guide me on How can I share it with you?

**Comment by MridulS** [comment]
You can create a Pull Request against this repository (networkx/notebooks) with your ipynb.

**Comment by Hetarth02** [comment]
I can't seem to get an idea on how to do so...? Exactly which folders do I compare or in which folder do I upload my file, what exactly do I do?

**Comment by Hetarth02** [comment]
@MridulS I managed to create a PR but it is showing a red cross on it. Is there any problem? If not, I have uploaded a jupyter notebook named Bipartite_basic_functions, do check it out and give me feedback on it.

**Comment by dschult** [comment]
The red x on the PR means that the automated tests didn't pass. 
That looks like it is an issue with the "master vs main" branch names in our CI testing system.
So, don't worry about that trouble for now. We're working to get that right.

**Comment by Hetarth02** [comment]
Oh! I see. Also, do check the notebook and guide me if it needs improvisation. Thanks, in advance!
