### ISSUE TITLE
Missing repository license 

### ISSUE THREAD

**Issue by stef4k** [networkx/notebooks#34]
There is no license file in this repository. I could create one if you could specify the license type.

**Comment by rossbar** [comment]
Ah nice catch. I assume we should add the same BSD-3 license used by NetworkX. Since this is mostly pedagogical material though, maybe there's a reason to use different licenses for text/data/code? I'm not familiar enough with the finer points to have an opinion... @stefanv do you have any thoughts on this?

**Comment by stefanv** [comment]
Here's what we have in the scikit-image tutorials repo:

> All materials in this repository are available free of restriction under the Creative Commons CC0 1.0 Universal Public Domain Dedication (see LICENSE.txt).

> However, we ask that you actively acknowledge and give attribution to this repo and to the authors if you reproduce them or create any derivative works. Specifically:

> Keep the CC0 Public Domain Dedication intact when reusing large portions of the material (such as an entire lecture), so that others may benefit from the same license you did.

> Do not represent yourself as the author of re-used material.

> For more information on these guidelines, which are sometimes known as CC0 (+BY), see this blog post by Dan Cohen.

Too much text, and most of it can be cut, but: I think it's worth giving a clear indication that you are fine with users re-using the code without worrying about a license when it comes to tutorials and data.

Recently, in a conversation on the NumFOCUS projects list, it became clear that CC0 is not all that simple.  But, I think the intent behind it is clear: we don't care about how you use this stuff, and we certainly won't follow up on it.

**Comment by stef4k** [comment]
Alright then, I will create a new LICENSE.txt file of the CC0 1.0 Universal, if that is okay.
